### PR TITLE
Missing $ in variables

### PR DESCRIPTION
**Pull request by alexiri**
Otherwise I get this in the logs:

sh: NGINX_WORKER_CONNECTIONS: unknown operand
sh: NGINX_WORKER_OPEN_FILES: unknown operand

### CODE REVIEW

**Comment by SDLyu** [comment]
I have the same issue

**Comment by ILoveYouDrZaius** [comment]
I had exactly this same problem and I came to do a PR to fix it. I hope tiangulo will read it and accept it.

Thank you.

**Comment by tiangolo** [comment]
Thanks for pointing out the error.

It was being produced because Alpine images have `sh` instead of `bash` in the lines like:

```bash
if [[ -v NGINX_WORKER_CONNECTIONS ]] ; then
```

And actually the lines like:

```bash
if [[ -v $NGINX_WORKER_CONNECTIONS ]] ; then
```

...would not work either.

---

But I just updated them to:

```bash
if [ -n "$NGINX_WORKER_CONNECTIONS" ] ; then
```

...which is compatible with `sh`. So it should be working now.

---

Could you please try with the latest version?

Let me know how it goes.

Thanks again for pointing out the issue!

**Comment by tiangolo** [comment]
I imagine the problem is now solved, so I'll close this PR.

**Pull request closed without merging**
